### ISSUE TITLE
undefined method 'set' for main:Object (NoMethodError)

### ISSUE THREAD

**Issue by kiddrew** [glyph-fr/capistrano-dotenv-tasks#4]
I just installed this gem and the cap tasks are working perfectly, but my rails generator is broken.  I'm getting this message:

```
/Users/andrew/.rvm/gems/ruby-2.2.4/gems/capistrano-dotenv-tasks-0.1.2/lib/capistrano/dotenv/tasks.rb:6:in `<top (required)>': undefined method `set' for main:Object (NoMethodError)
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `require'
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `rescue in block in require'
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:68:in `block in require'
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
    from /Users/andrew/Development/ilf-cms/config/application.rb:7:in `<top (required)>'
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application.rb:82:in `require'
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application.rb:82:in `preload'
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application.rb:143:in `serve'
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application.rb:131:in `block in run'
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application.rb:125:in `loop'
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application.rb:125:in `run'
    from /Users/andrew/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /Users/andrew/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/andrew/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'
```

**Comment by kiddrew** [comment]
False alarm.  Missed the `require: false` in the Gemfile.
